spring:
  application:
    name: accepted-assignment

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/matchOdds

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080